// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7vnMaDmPxc-JarsBStPt4yjdzRrJcCj0',
    appId: '1:714168073749:web:8f18750550edb72f42d81c',
    messagingSenderId: '714168073749',
    projectId: 'fusion-app-3c3e4',
    authDomain: 'fusion-app-3c3e4.firebaseapp.com',
    storageBucket: 'fusion-app-3c3e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnlOa94n9r-0kn9uhNSxh8Zqer2l44cQc',
    appId: '1:714168073749:android:dc27a0d0a747356942d81c',
    messagingSenderId: '714168073749',
    projectId: 'fusion-app-3c3e4',
    storageBucket: 'fusion-app-3c3e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UPX_0Kbnv0n-ZpAt34fm0QII3rzvMUE',
    appId: '1:714168073749:ios:3e9374f21c7e2f9242d81c',
    messagingSenderId: '714168073749',
    projectId: 'fusion-app-3c3e4',
    storageBucket: 'fusion-app-3c3e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UPX_0Kbnv0n-ZpAt34fm0QII3rzvMUE',
    appId: '1:714168073749:ios:3e9374f21c7e2f9242d81c',
    messagingSenderId: '714168073749',
    projectId: 'fusion-app-3c3e4',
    storageBucket: 'fusion-app-3c3e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7vnMaDmPxc-JarsBStPt4yjdzRrJcCj0',
    appId: '1:714168073749:web:9999edf3b276961042d81c',
    messagingSenderId: '714168073749',
    projectId: 'fusion-app-3c3e4',
    authDomain: 'fusion-app-3c3e4.firebaseapp.com',
    storageBucket: 'fusion-app-3c3e4.firebasestorage.app',
  );
}
